
version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.2.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  node:
    image: prom/node-exporter
    ports:
      - 9100:9100
